AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/TrivialAccessors:
  AllowPredicates: true

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
