language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.0
before_install: gem install bundler -v 1.11.2
notifications:
  email:
    - support@travellink.com.au
  flowdock:
    secure: aayRwHDb8ZfboD41FdpqNT0dxvrfyzqRknSwTiNlwqzEWvTFYlqCwDbU7OGt0Fn8YRUg8+zq9ZrbJAEwn53zL/Vn3vireIw9iEYti59e6UynLD6eQOu5k1LVGDk1XLL5Mh8iZ9CQ7GOvPubutdzZAZ721gFO81K2hxSq4f7vU5YCjsuRfPfqh/vA6R8YmsPfTClu/pLsP1GsuEx6/Jkyb7fkcte5fg7G2DFEJ7tVCQabRZqOHnJZsrKB9n3bq8wccibMXYEkIYzMXCo9lD+HGyyUtLI3EHfD1B7KlilAgbacZelBUtk5J6HYajJn/2pqglsXXAkBpeyz9ZV4v8k89miS4nzzaqvQFM5hfk8cPH2jcP+ZvaOQNKg95PGiFBd/yvpoE5fJaePEqintr9x1mraHKd+cvVh02Khh3sXubeRvZnbPRewqT+14A1+JPEnpjXB1GvbazKX9VYMprDrrFDDDkl/tGUkZvDwXgUGpnrf9xS1iskBhaZxHHLXY+nUj85NjS0q6FgCdI9iPuHtDsdh4A9a3FCHqrXlSsgr580ySI0D8Kdi0JdZuP9bYZAALQ+Kf4OK4MlQ9iaZUCUu20Ld1ssQ7i2aBgbb1XIVyKSv8MK7ybP8zZwSEs45uBED3qw0bQQPxKt2JypgvhCcwBEDn34xVAm28k/seS6iS5ds=
sudo: false
cache: bundler
